<a href="https://colab.research.google.com/github/brainmentorspvtltd/ML_OnlineFDP/blob/master/DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# !pip install nltk

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import urllib.request as url
import json

In [0]:
# !pip install seaborn

Numpy Introduction
- Used for nd array
- Used mathematical operations

In [0]:
x = np.array([2,44,6,8,2,21,45,8,2])

In [6]:
print(x)

[ 2 44  6  8  2 21 45  8  2]


In [0]:
x = np.array([[1,2,4,6], [4,6,2,6], [12,21,4,76]])

In [8]:
x

array([[ 1,  2,  4,  6],
       [ 4,  6,  2,  6],
       [12, 21,  4, 76]])

In [9]:
x.shape

(3, 4)

In [10]:
x[0]

array([1, 2, 4, 6])

In [11]:
x[0][1]

2

In [13]:
# slicing of array
x[0:2]

array([[1, 2, 4, 6],
       [4, 6, 2, 6]])

In [16]:
x[:,0:1]

array([[ 1],
       [ 4],
       [12]])

In [17]:
x[:,0]

array([ 1,  4, 12])

In [18]:
x[1:3,1:3]

array([[ 6,  2],
       [21,  4]])

In [19]:
np.random.random()

0.664131368458091

In [20]:
np.random.random(size = (4,4))

array([[0.99923841, 0.4730705 , 0.12805686, 0.74552296],
       [0.55785296, 0.33830319, 0.64284647, 0.87030043],
       [0.27204587, 0.86826709, 0.83990001, 0.04748916],
       [0.25817955, 0.25926975, 0.67446041, 0.82680033]])

In [0]:
x = np.array([2,4,6,7])
y = np.array([7,8,5,3])

In [22]:
x + y

array([ 9, 12, 11, 10])

Pandas Introduction

In [0]:
response = url.urlopen('https://api.covid19india.org/states_daily.json')

In [24]:
response

In [0]:
json_data = json.load(response)

In [0]:
json_data