In [1]:
!pip install numpy

In [2]:
a = 12
b = 12
c = a + b

In [3]:
# to execute cell = shift + enter

### Python introduction

In [6]:
a * b

144

In [5]:
a - b

0

In [7]:
import numpy as np

In [8]:
np.random.randint(1,10)

9

In [9]:
np.random.randint(1,10,5)

array([8, 6, 6, 9, 3])

In [10]:
np.random.randint(1,100,(4,4))

array([[31, 88, 31, 93],
       [21, 36, 51, 84],
       [13, 95, 35,  5],
       [99, 28, 45,  6]])

In [11]:
np.random.randn()

-0.2103503650952044

In [13]:
np.random.randn(5,5)

array([[-0.06627531, -1.73658348, -0.97708151,  0.53203925,  0.6563045 ],
       [ 1.53381443,  1.04103305, -1.73812913, -0.26614168, -0.17209034],
       [ 0.98211232,  0.38170814, -0.00877454,  1.01858439,  1.8208246 ],
       [-0.65025396,  1.17228452, -0.33669637, -0.82565073, -0.33512644],
       [-0.05022843, -0.51315844,  0.44232091,  0.47810052, -0.09840944]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# start,stop,step
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [19]:
np.random.randint(1,100)

10

In [20]:
np.random.seed(5)
np.random.randint(1,100)

79

In [21]:
# pseudo random
np.random.seed(10)
data = np.random.randint(100,1000,50)

In [22]:
data

array([365, 225, 627, 420, 469, 223, 256, 833, 596, 981, 108, 173, 356,
       590, 140, 602, 520, 471, 628, 456, 339, 495, 154, 444, 463, 222,
       674, 645, 300, 968, 789, 791, 154, 177, 553, 113, 855, 509, 482,
       753, 960, 442, 898, 770, 189, 752, 421, 643, 925, 904])

In [23]:
np.max(data)

981

In [24]:
# will return the index of maximum value
np.argmax(data)

9

In [25]:
np.min(data)

108

In [26]:
np.argmin(data)

10

In [27]:
data.shape

(50,)

In [28]:
np.reshape(data,(5,10))

array([[365, 225, 627, 420, 469, 223, 256, 833, 596, 981],
       [108, 173, 356, 590, 140, 602, 520, 471, 628, 456],
       [339, 495, 154, 444, 463, 222, 674, 645, 300, 968],
       [789, 791, 154, 177, 553, 113, 855, 509, 482, 753],
       [960, 442, 898, 770, 189, 752, 421, 643, 925, 904]])

In [29]:
data_2 = np.reshape(data,(5,10))

In [31]:
# data.reshape((5,10))